Make pv names consistent with web gui names
PandABlocks/PandABlocks-ioc pull request #26
Opened 2023-08-11 09:23 UTC by evalott100

A copy of https://github.com/PandABlocks/PandABlocks-ioc/pull/18, but branched off of the [improved testing branch](https://github.com/evalott100/PandABlocks-ioc/tree/adjust_testing_environment).

2023-08-21 08:00 UTC, AlexanderWells-diamond requested changes
The code changes all look fine to me, although note I don't know much about PVI.

There's a few bits I think need cleaning up regarding testing. If I understand it correctly, we now have no tests that include numbered blocks. I think we need at least one, just to prove that mechanism works.

2023-08-21 08:02 UTC, AlexanderWells-diamond commented
On a related note, have you seen the discussions happening in Ophyd at the moment regarding similar changing of block names? See [this comment](https://github.com/bluesky/ophyd-epics-devices/pull/39#issuecomment-1684027686).

2023-08-21 08:35 UTC, evalott100 commented on tests/test_ioc_system.py
> +        await caget(TEST_PREFIX + ":SEQ:TABLE:OUTD2", timeout=1)
That the `mocked_panda_multiple_seq_responses` with a `number=2` in the block gives you a `SEQ1` and a `SEQ2` once the ioc starts up, with independent values. we also double check a `SEQ` PV isn't broadcasted.

2023-08-21 08:37 UTC, AlexanderWells-diamond commented on tests/test_ioc_system.py
> +        await caget(TEST_PREFIX + ":SEQ:TABLE:OUTD2", timeout=1)
I see, that makes sense. Probably worth a comment to say that.

2023-08-21 08:39 UTC, RAYemelyanova commented
Yep; just to chime in, I do think it makes more sense for the PandA to have either names and numbers on their blocks or just names, e.g.

PCAP
PULSE1
PULSE2
SEQ1
SEQ2

but not, for example,

sfp2_sync_in
sfp2_sync_in1

as seems to be happening [here](https://github.com/bluesky/ophyd-epics-devices/issues/38#issue-1843663248)

2023-08-21 08:44 UTC, evalott100 commented on tests/test_ioc_system.py
> +    """Test that the Arm and Disarm commands are correctly sent to PandA"""
It checks the softioc has broadcasted the correct PVs, suffixed with the correct numbers.

The `command_queue` wouldn't contain any relevant information to this,  the responses from the mocked_panda are hardcoded.

2023-08-21 08:46 UTC, evalott100 commented on tests/test_ioc_system.py
> +    """Test that the Arm and Disarm commands are correctly sent to PandA"""
Just realised the docstring is a copy, I'll rewrite it.

2023-08-21 13:14 UTC, evalott100 commented on src/pandablocks_ioc/_tables.py
> +        )
I'm unsure myself: it's included from what Tom did in the `fixes` branch [here](https://github.com/PandABlocks/PandABlocks-ioc/blob/fixes/src/pandablocks_ioc/_tables.py#L269-L279)

2023-08-21 13:27 UTC, GDYendell commented on src/pandablocks_ioc/_tables.py
> +        )
Ophyd uses this to find the PVs that the IOC has available and create the interface to them on the ophyd Device. So, the root `:PVI` is just a PVI PV for each block:

```
{'sfp2_sync_in': {'d': 'PANDA:SFP2_SYNC_IN:PVI'}, 'srgate2': {'d': 'PANDA:SRGATE2:PVI'}, 'srgate1': {'d': 'PANDA:SRGATE1:PVI'}, 'sfp3_sync_out': {'d': 'PANDA:SFP3_SYNC_OUT:PVI'}, 'sfp3_sync_in': {'d': 'PANDA:SFP3_SYNC_IN:PVI'}, 'sfp2_sync_out': {'d': 'PANDA:SFP2_SYNC_OUT:PVI'}, 'srgate3': {'d': 'PANDA:SRGATE3:PVI'}, 'seq2': {'d': 'PANDA:SEQ2:PVI'}, 'seq1': {'d': 'PANDA:SEQ1:PVI'}, 'pulse4': {'d': 'PANDA:PULSE4:PVI'}, 'pulse3': {'d': 'PANDA:PULSE3:PVI'}, 'pulse2': {'d': 'PANDA:PULSE2:PVI'}, 'pulse1': {'d': 'PANDA:PULSE1:PVI'}, 'pgen2': {'d': 'PANDA:PGEN2:PVI'}, ...}
```
and then, for example, the `:PCAP:PVI` contains:
```
{'health': {'r': 'PANDA:PCAP:HEALTH'}, 'ts_trig_capture': {'rw': 'PANDA:PCAP:TS_TRIG:CAPTURE'}, 'ts_start_capture': {'rw': 'PANDA:PCAP:TS_START:CAPTURE'}, 'ts_end_capture': {'rw': 'PANDA:PCAP:TS_END:CAPTURE'}, 'trig_edge': {'rw': 'PANDA:PCAP:TRIG_EDGE'}, 'trig_delay': {'rw': 'PANDA:PCAP:TRIG:DELAY'}, 'trig': {'rw': 'PANDA:PCAP:TRIG'}, 'shift_sum': {'rw': 'PANDA:PCAP:SHIFT_SUM'}, 'samples_capture': {'rw': 'PANDA:PCAP:SAMPLES:CAPTURE'}, 'active': {'r': 'PANDA:PCAP:ACTIVE'}, 'gate_delay': {'rw': 'PANDA:PCAP:GATE:DELAY'}, 'gate': {'rw': 'PANDA:PCAP:GATE'}, 'enable_delay': {'rw': 'PANDA:PCAP:ENABLE:DELAY'}, 'enable': {'rw': 'PANDA:PCAP:ENABLE'}, ...}
```

2023-08-21 13:38 UTC, GDYendell commented on src/pandablocks_ioc/_tables.py
> +        )
I am not sure what the `table_name + ":PV",` longStringIn record itself is, though. @evalott100 ?

2023-08-21 14:39 UTC, GDYendell commented on src/pandablocks_ioc/_tables.py
> +        )
I think it exists purely to add `PANDA:SEQ1:TABLE` - which is a V4 PV produced by the IOC - to the PVI structure.

2023-08-23 10:17 UTC, evalott100 commented on tests/test_ioc_system.py
> -    assert _ensure_block_number_present("JKL1.MNOP") == "JKL1.MNOP"
I've added a check on `introspect_panda` to ensure block names don't have any numbers in the strings at all

2023-08-23 10:46 UTC, AlexanderWells-diamond commented on tests/test_ioc_system.py
> -    assert _ensure_block_number_present("JKL1.MNOP") == "JKL1.MNOP"
Can you confirm how the code in https://github.com/PandABlocks/PandABlocks-ioc/commit/81e8ecef4d20b15ec9ae2a62cbfef2c46e234eef handles block names of the form "SFP2_SYNC_IN"? From a quick glance it looks like that'll trip the regex when it is actually a valid block name. There should also probably be a test for block names of this form. 

I think I saw very similar code to this in the Ophyd PR I linked.

2023-08-23 12:47 UTC, evalott100 commented
> Yep; just to chime in, I do think it makes more sense for the PandA to have either names and numbers on their blocks or just names, e.g.
> 
> PCAP PULSE1 PULSE2 SEQ1 SEQ2
> 
> but not, for example,
> 
> sfp2_sync_in sfp2_sync_in1
> 
> as seems to be happening [here](https://github.com/bluesky/ophyd-epics-devices/issues/38#issue-1843663248)
> 
> In fact if you have a look at that whole thread it looks like there's a mismatch between the panda blocks on malcolm and what we see via PVI. And I wonder if we can explain why 🤔


I'll chat to  @coretl about what we want our behaviour to be. In this PR I've caused the softioc to throw an error if the user tries to have a number in the block name (rather than passing `number=`).

2023-08-29 15:04 UTC, coretl commented
To update this ticket, the outcome was that we should never have both `sfp2_sync_in` and `sfp2_sync_in1`, that is a bug. All entries should be under `sfp2_sync_in`. @evalott100 is working on a PR to fix this.

2023-09-01 08:21 UTC, AlexanderWells-diamond approved these changes
Looks good! A couple of minor nitpicks but nothing show stopping.

2023-09-01 08:21 UTC, AlexanderWells-diamond commented on tests/test_ioc.py
> +            timeout=0.3,
Pedantic, but I'm guessing Black isn't running on these test files? These lines look kinda ugly.

2023-09-01 08:21 UTC, AlexanderWells-diamond commented on tests/test_ioc.py
> +            timeout=0.5,
See above comment about Black formatting

2023-09-01 08:25 UTC, coretl commented on src/pandablocks_ioc/_pvi.py
> +        # # TODO: What should the label be?
no, this will be answered when we have PVI entries for things like the positions table

2023-09-01 08:26 UTC, evalott100 commented on src/pandablocks_ioc/_types.py
> +        # Device is a metadata_label field
I'll correct it to `# Field is a '*METADATA_LABEL'`

2023-09-01 08:27 UTC, coretl commented on src/pandablocks_ioc/_tables.py
> +            putorder = 0 if action == TableModeEnum.EDIT else putorder_index
Yes, this is `len(self.table_fields_records)`

2023-09-01 08:30 UTC, coretl commented on src/pandablocks_ioc/_tables.py
> +        putorder_index = 1
Prompted by @AlexanderWells-diamond comments, we could get rid of this variable and instead do:

```python
for i, (field_name, field_record_container) in enumerate(self.table_fields_records.items()):
    ...
    field_pva_info = {
        "+type": "plain",
        "+channel": "VAL",
        "+putorder": i + 1,
        "+trigger": "",
    }
    ...
    # For the last column in the table
    if i == len(self.table_fields_records) - 1:
        ...
```

2023-09-01 08:31 UTC, coretl commented on src/pandablocks_ioc/_types.py
> +        # Device is a metadata_label field
```suggestion
        # Field is the label for the block, which is stored in the special *METADATA area
```

2023-09-01 09:03 UTC, evalott100 commented on src/pandablocks_ioc/ioc.py
> +    (all_records, all_values_dict, panda_dict) = await create_records(
Changing it to 
``` python
    block_info_dict = {key: value.block_info for key, value in panda_dict.items()}
    return (all_records, all_values_dict, block_info_dict)
```

2023-09-01 09:11 UTC, evalott100 commented on tests/test_ioc.py
> +            timeout=0.5,
See above

2023-09-01 13:07 UTC, merged