Removed scalar and index fields
PandABlocks/PandABlocks-ioc pull request #71
Opened 2023-11-02 16:01 UTC by evalott100

Closes #70

2023-11-02 16:04 UTC, evalott100 commented
SEQ table before:
![image](https://github.com/PandABlocks/PandABlocks-ioc/assets/21142790/c6e47871-cb8a-4dda-aaf3-1acc8f3a83d3)
and after
![image](https://github.com/PandABlocks/PandABlocks-ioc/assets/21142790/8aea5ce1-16e7-4c5a-bcfb-3148d59eb975)

2023-11-03 08:51 UTC, coretl approved these changes

2023-11-03 08:51 UTC, coretl commented on src/pandablocks_ioc/ioc.py
> +            ),
Not sure why there was a trailing comma here...
```suggestion
            )
```

2023-11-03 09:00 UTC, AlexanderWells-diamond requested changes
Unless I've misunderstood something, there are still references left to both SCALAR and INDEX records in the codebase. A short list includes:
- `TableUpdater.table_scalar_records`
- In test_tables.py `table_updater` contains `updater.index_record` mocking. 

Please check through all occurrences of the word "scalar" and "index" to ensure all references have been cleaned up.

2023-11-03 15:52 UTC, evalott100 commented
> Unless I've misunderstood something, there are still references left to both SCALAR and INDEX records in the codebase. A short list includes:
> 
>     * `TableUpdater.table_scalar_records`
> 
>     * In test_tables.py `table_updater` contains `updater.index_record` mocking.
> 
> 
> Please check through all occurrences of the word "scalar" and "index" to ensure all references have been cleaned up.

Apologies accidentally didn't push some work before I asked Tom for review.

2023-11-03 15:57 UTC, AlexanderWells-diamond approved these changes
Delete the one extra comment then this looks good to go.

2023-11-03 15:57 UTC, AlexanderWells-diamond commented on src/pandablocks_ioc/_tables.py
>      # Collection of the records that comprise the SCALAR records for each field
This comment should be deleted

2023-11-03 16:02 UTC, merged