Adopt python-copier-template 1.0.0
PandABlocks/PandABlocks-ioc pull request #98
Opened 2024-02-29 11:02 UTC by evalott100

2024-03-01 11:22 UTC, evalott100 commented
Docs publishing working fine here: https://pandablocks.github.io/PandABlocks-ioc/98_merge/index.html

2024-03-01 13:46 UTC, coretl requested changes
Please can you put the Dockerfile from copier in here instead of the epics-containers one, then put the action back to the copier one too?

2024-03-01 13:46 UTC, coretl commented on src/pandablocks_ioc/__init__.py
> +__version__ = version("pandablocks-ioc")
```suggestion
from ._version import __version__
```

2024-03-01 13:46 UTC, coretl commented on src/pandablocks_ioc/__init__.py
> +from importlib.metadata import version  # noqa
```suggestion
```

2024-03-04 09:39 UTC, evalott100 commented
Changes were made [here](https://github.com/evalott100/PandABlocks-ioc/commit/082eedd667c7112d50e59829fd8a81775ce22bef) to try to use the published container CI in a test environment.

We decided to abandon this and use the same container CI as the copier template.

2024-03-04 09:55 UTC, coretl approved these changes

2024-03-04 09:57 UTC, merged